### PR TITLE
DB for transcripts

### PR DESCRIPTION
**Pull request by iskandr**
Instead of using `pyfaidx` to wrap a FASTA index file for reference transcripts, instead using `biopython` to create a `sqlite3` database of transcripts. This is preferable since we don't have to convert between `Bio.Seq` objects (used in Varcode), Python strings, and `pyfaidx` sequences (which have a different API than BioPython). This should, theoretically, eventually be faster (though the performance is currently dominated by other code).

Also, I pulled out the benchmarking code used by `test_timings.py` into a small library called `tinytimer` (which I can reuse in Varcode). 

[Review on Reviewable](https://reviewable.io/reviews/hammerlab/pyensembl/68)

### CODE REVIEW

**Comment by tavinathanson** [comment]
Started commenting this up on Friday but didn't finish. I'll shoot be done tomorrow AM, sorry for the delay.

**Comment by tavinathanson** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/hammerlab/pyensembl/68)

Reviewed files:
- pyensembl/reference_transcripts.py @ r1
- pyensembl/transcript.py @ r1
- README.md @ r1
- requirements.txt @ r1
- setup.py @ r1
- test/test_download.py @ r1
- test/test_reference_transcripts.py @ r1
- test/test_timings.py @ r1
- test/test_transcript_objects.py @ r1
- test/timer.py @ r1





---

<sup>**[pyensembl/reference_transcripts.py, line 76 \[r1\]](https://reviewable.io:443/reviews/hammerlab/pyensembl/68#-JlBnfDpn5_psE8ZOxnb)** ([raw file](https://github.com/hammerlab/pyensembl/blob/963e4244853a99060c9b0396b7354992322be8a6/pyensembl/reference_transcripts.py#L76)):</sup>
So `_fasta_keys` was created because of a pyfaidx quirk, but now you're still finding it useful so you don't need to go to SQLite for `__contains__`?

---

<sup>**[pyensembl/reference_transcripts.py, line 102 \[r1\]](https://reviewable.io:443/reviews/hammerlab/pyensembl/68#-JlBtfTt68PxfO7gYZUB)** ([raw file](https://github.com/hammerlab/pyensembl/blob/524b4b829fdec5073a59bbc626fc8dee849b05b5/pyensembl/reference_transcripts.py#L102)):</sup>
Why are we getting rid of this?

---

<sup>**[pyensembl/reference_transcripts.py, line 135 \[r1\]](https://reviewable.io:443/reviews/hammerlab/pyensembl/68#-JlBugI1jDqhlydSVPLl)** ([raw file](https://github.com/hammerlab/pyensembl/blob/963e4244853a99060c9b0396b7354992322be8a6/pyensembl/reference_transcripts.py#L135)):</sup>
The BioPython examples show `records.get("Missing", None)`http://biopython.org/DIST/docs/api/Bio.SeqIO-module.html#index_db so I just want to make sure that `get` without `, None` will return `None`?

---

<sup>**[pyensembl/reference_transcripts.py, line 172 \[r1\]](https://reviewable.io:443/reviews/hammerlab/pyensembl/68#-JlBuzvCWKEfvWSq-xmC)** ([raw file](https://github.com/hammerlab/pyensembl/blob/963e4244853a99060c9b0396b7354992322be8a6/pyensembl/reference_transcripts.py#L172)):</sup>
Update the comment? Also, `ensembl_release` currently relies on this method returning True or False.

---

<sup>**[pyensembl/reference_transcripts.py, line 179 \[r1\]](https://reviewable.io:443/reviews/hammerlab/pyensembl/68#-JlBvy7BIu23ZTz7Sf2n)** ([raw file](https://github.com/hammerlab/pyensembl/blob/963e4244853a99060c9b0396b7354992322be8a6/pyensembl/reference_transcripts.py#L179)):</sup>
Update comment

---

<sup>**[pyensembl/reference_transcripts.py, line 186 \[r1\]](https://reviewable.io:443/reviews/hammerlab/pyensembl/68#-JlBwQJWiBKsGB8pQrjG)** ([raw file](https://github.com/hammerlab/pyensembl/blob/963e4244853a99060c9b0396b7354992322be8a6/pyensembl/reference_transcripts.py#L186)):</sup>
So we're removing on force "indexing", but then not actually "indexing"?

Edit: oh, I guess it'll happen on ` return self._fasta_dictionary`? Maybe clarify that with a comment?

---

<sup>**[pyensembl/reference_transcripts.py, line 192 \[r1\]](https://reviewable.io:443/reviews/hammerlab/pyensembl/68#-JlBv_pzpDekruQhP0mw)** ([raw file](https://github.com/hammerlab/pyensembl/blob/963e4244853a99060c9b0396b7354992322be8a6/pyensembl/reference_transcripts.py#L192)):</sup>
Why not just check for the existence of the db? I guess this is more pythonic? Bleh.

---

<sup>**[pyensembl/reference_transcripts.py, line 196 \[r1\]](https://reviewable.io:443/reviews/hammerlab/pyensembl/68#-JlBwATYsv3OUSf9YfLD)** ([raw file](https://github.com/hammerlab/pyensembl/blob/963e4244853a99060c9b0396b7354992322be8a6/pyensembl/reference_transcripts.py#L196)):</sup>
Yuck. Is the issue that the error message is a BioPython error message and not under your control?

---

<sup>**[setup.py, line 70 \[r1\]](https://reviewable.io:443/reviews/hammerlab/pyensembl/68#-JlBxB-aogJSCP_9AIZJ)** ([raw file](https://github.com/hammerlab/pyensembl/blob/963e4244853a99060c9b0396b7354992322be8a6/setup.py#L70)):</sup>
tinytimer not included because it's just for testing?

---

<sup>**[test/test_download.py, line 12 \[r1\]](https://reviewable.io:443/reviews/hammerlab/pyensembl/68#-JktBvr6iyl_PmyQV1Gc)** ([raw file](https://github.com/hammerlab/pyensembl/blob/524b4b829fdec5073a59bbc626fc8dee849b05b5/test/test_download.py#L12)):</sup>
The purpose of these tests (to test DB creation based on downloaded FASTA information, and making sure a new DB only gets created when we expect) still seems valid, no?

---

**Comment by iskandr** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/hammerlab/pyensembl/68)







---

<sup>**[pyensembl/reference_transcripts.py, line 76 \[r1\]](https://reviewable.io:443/reviews/hammerlab/pyensembl/68#-JlBnfDpn5_psE8ZOxnb)** ([raw file](https://github.com/hammerlab/pyensembl/blob/963e4244853a99060c9b0396b7354992322be8a6/pyensembl/reference_transcripts.py#L76)):</sup>
Yep

---

<sup>**[pyensembl/reference_transcripts.py, line 102 \[r1\]](https://reviewable.io:443/reviews/hammerlab/pyensembl/68#-JlBtfTt68PxfO7gYZUB)** ([raw file](https://github.com/hammerlab/pyensembl/blob/524b4b829fdec5073a59bbc626fc8dee849b05b5/pyensembl/reference_transcripts.py#L102)):</sup>
It does something surprising by clearing the whole cache (not just the cached reference transcripts). Since we're not currently using this method anywhere, and an external user can accomplish the same thing via `EnsemblRelease.clear_cache()`, it seemed unnecessary. 

---

<sup>**[pyensembl/reference_transcripts.py, line 135 \[r1\]](https://reviewable.io:443/reviews/hammerlab/pyensembl/68#-JlBugI1jDqhlydSVPLl)** ([raw file](https://github.com/hammerlab/pyensembl/blob/963e4244853a99060c9b0396b7354992322be8a6/pyensembl/reference_transcripts.py#L135)):</sup>
```
In [21]: db = index_db("test.db", "/Users/iskander/Library/Caches/ensembl/Homo_sapiens.GRCh37.75.cdna.all.fa", "fasta")

In [22]: x = db.get("Missing")

In [23]: print(x)
None
```

---

<sup>**[pyensembl/reference_transcripts.py, line 172 \[r1\]](https://reviewable.io:443/reviews/hammerlab/pyensembl/68#-JlBuzvCWKEfvWSq-xmC)** ([raw file](https://github.com/hammerlab/pyensembl/blob/963e4244853a99060c9b0396b7354992322be8a6/pyensembl/reference_transcripts.py#L172)):</sup>
I'm going to change `EnsemblRelease` to not expect to know whether indexing happened or not (since `Bio.Seq.index_db` won't tell us) and it's not really that important to print something *after* it's already done.

---

<sup>**[pyensembl/reference_transcripts.py, line 186 \[r1\]](https://reviewable.io:443/reviews/hammerlab/pyensembl/68#-JlBwQJWiBKsGB8pQrjG)** ([raw file](https://github.com/hammerlab/pyensembl/blob/963e4244853a99060c9b0396b7354992322be8a6/pyensembl/reference_transcripts.py#L186)):</sup>
It happens when I call `Bio.Seq.index_db`in  `_create_or_open_fasta_db` and the database file doesn't exist yet. I'll comment this a little more. 

---

<sup>**[pyensembl/reference_transcripts.py, line 192 \[r1\]](https://reviewable.io:443/reviews/hammerlab/pyensembl/68#-JlBv_pzpDekruQhP0mw)** ([raw file](https://github.com/hammerlab/pyensembl/blob/963e4244853a99060c9b0396b7354992322be8a6/pyensembl/reference_transcripts.py#L192)):</sup>
Because the database may be malformed and since I'm not using `datacache` to construct it I have no way to check if it's complete without poking around the potentially unstable internals of BioPython. 

Agreed that this is a bit gross. 

---

<sup>**[pyensembl/reference_transcripts.py, line 196 \[r1\]](https://reviewable.io:443/reviews/hammerlab/pyensembl/68#-JlBwATYsv3OUSf9YfLD)** ([raw file](https://github.com/hammerlab/pyensembl/blob/963e4244853a99060c9b0396b7354992322be8a6/pyensembl/reference_transcripts.py#L196)):</sup>
Yeah, it's just a ValueError and I don't have any way to get anything more specific. 

---

<sup>**[setup.py, line 70 \[r1\]](https://reviewable.io:443/reviews/hammerlab/pyensembl/68#-JlBxB-aogJSCP_9AIZJ)** ([raw file](https://github.com/hammerlab/pyensembl/blob/963e4244853a99060c9b0396b7354992322be8a6/setup.py#L70)):</sup>
Yep

---

<sup>**[test/test_download.py, line 12 \[r1\]](https://reviewable.io:443/reviews/hammerlab/pyensembl/68#-JktBvr6iyl_PmyQV1Gc)** ([raw file](https://github.com/hammerlab/pyensembl/blob/524b4b829fdec5073a59bbc626fc8dee849b05b5/test/test_download.py#L12)):</sup>
I like the broad purpose (though the specifics are now different since we're not making `fai` files) but I'm not sure I like testing deep implementation details like this: it makes the code much harder to refactor and this is a particularly volatile part of PyEnsembl that will definitely change a few more times.

It would be more flexible and maintainable to actually test for the existence of the database path (which is exposed as part of the API). 

Added a related issue: https://github.com/hammerlab/pyensembl/issues/69

---

**Comment by tavinathanson** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/hammerlab/pyensembl/68)

Reviewed files:
- pyensembl/ensembl_release.py @ r2
- pyensembl/reference_transcripts.py @ r2

---

Looks good to me, I guess EnsemblRelease still needs to be updated to reflect the change in logic?

---

<sup>**[pyensembl/ensembl_release.py, line 154 \[r2\]](https://reviewable.io:443/reviews/hammerlab/pyensembl/68#-JlC8VmrSjHtwEr5hDl-)** ([raw file](https://github.com/hammerlab/pyensembl/blob/1760eb52c6cfe87ed4d76933184f1b0497534a08/pyensembl/ensembl_release.py#L154)):</sup>
Whoa, huh? Why did I create `index` and `_index` instead of just using a default. Very odd.

---

<sup>**[pyensembl/ensembl_release.py, line 165 \[r2\]](https://reviewable.io:443/reviews/hammerlab/pyensembl/68#-JlC7_WaVThH-v65CZiN)** ([raw file](https://github.com/hammerlab/pyensembl/blob/1760eb52c6cfe87ed4d76933184f1b0497534a08/pyensembl/ensembl_release.py#L165)):</sup>
We probably want to apply your new logic to this guy, too. But I'm okay with that being separate.

---

<sup>**[pyensembl/reference_transcripts.py, line 172 \[r1\]](https://reviewable.io:443/reviews/hammerlab/pyensembl/68#-JlBuzvCWKEfvWSq-xmC)** ([raw file](https://github.com/hammerlab/pyensembl/blob/963e4244853a99060c9b0396b7354992322be8a6/pyensembl/reference_transcripts.py#L172)):</sup>
It was my attempt to unify some logging in a central location, but I hear you!

---

<sup>**[pyensembl/reference_transcripts.py, line 186 \[r1\]](https://reviewable.io:443/reviews/hammerlab/pyensembl/68#-JlBwQJWiBKsGB8pQrjG)** ([raw file](https://github.com/hammerlab/pyensembl/blob/963e4244853a99060c9b0396b7354992322be8a6/pyensembl/reference_transcripts.py#L186)):</sup>
:+1:

---

<sup>**[test/test_download.py, line 12 \[r1\]](https://reviewable.io:443/reviews/hammerlab/pyensembl/68#-JktBvr6iyl_PmyQV1Gc)** ([raw file](https://github.com/hammerlab/pyensembl/blob/524b4b829fdec5073a59bbc626fc8dee849b05b5/test/test_download.py#L12)):</sup>
:+1:

---

**Comment by iskandr** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/hammerlab/pyensembl/68)



---

Remind me, what's missing from EnsemblRelease?

---

<sup>**[pyensembl/ensembl_release.py, line 154 \[r2\]](https://reviewable.io:443/reviews/hammerlab/pyensembl/68#-JlC8VmrSjHtwEr5hDl-)** ([raw file](https://github.com/hammerlab/pyensembl/blob/1760eb52c6cfe87ed4d76933184f1b0497534a08/pyensembl/ensembl_release.py#L154)):</sup>
No idea :-)

---

<sup>**[pyensembl/ensembl_release.py, line 165 \[r2\]](https://reviewable.io:443/reviews/hammerlab/pyensembl/68#-JlC7_WaVThH-v65CZiN)** ([raw file](https://github.com/hammerlab/pyensembl/blob/1760eb52c6cfe87ed4d76933184f1b0497534a08/pyensembl/ensembl_release.py#L165)):</sup>
Yeah, it makes sense to make the logging more standardized. 

---

**Comment by tavinathanson** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/hammerlab/pyensembl/68)



---

Nevermind, I misread, carry on!

---

**Pull request merged**
