### PR TITLE
WIP: Testing builds within Docker images

### PR DESCRIPTION
**Pull request by armish**
Experimental purposes only. Do not merge yet.

---
This change is [Reviewable](https://reviewable.io/reviews/hammerlab/pyensembl/158)

### CODE REVIEW

**Comment by iskandr** [comment]
@armish I've seen some other folks name unfinished branches like "WIP: Testing builds within Docker images" and then remove the "WIP" once you're done. Not sure if that alleviates worries about a premature merge but I've started doing it.

**Comment by iskandr** [comment]
Did this end up not working out?

**Comment by armish** [comment]
@iskandr: yeah, it came with some other complications that I haven't anticipated. @ryan-williams's recent suggestion about using Travis's cache mechanism sounds promising, though.

**Comment by tavinathanson** [comment]
What was @ryan-williams's suggestion about using Travis's cache mechanism? We had earlier talked about using that to cache the raw Ensembl data, however it would still need to be downloaded locally to the Travis node running the tests, and then the DB would still need to be built.

Maybe @ryan-williams's suggestion was to cache the DB itself via Travis's cache? We initially were hesitant to do that since the DB might keep changing, but I guess we did warm up to that idea in conversations about this Docker image approach?

**Comment by iskandr** [comment]
@ryan-williams @armish @tavinathanson If we add the database schema version to the path and then cache on Travis, then maybe (fingers crossed) it would be OK?

**Comment by tavinathanson** [comment]
@iskandr interesting idea! Other than forgetting to update the schema version, I don't see any obvious issues there?

**Pull request closed without merging**
