### PR TITLE
added Timer class and benchmark unit tests

### PR DESCRIPTION
**Pull request by iskandr**
Currently only testing performance of  `genes_at_locus`, `transcripts_at_locus`, `exons_at_locus` but should be easy to add more later. Also, there's a hackish search through the globals dict to find all benchmarks when they're being run outside of nose. If we need to reuse that trick elsewhere, I'll factor it out into its own module. 

[Review on Reviewable](https://reviewable.io/reviews/hammerlab/pyensembl/48)

### CODE REVIEW

**Comment by tavinathanson** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/hammerlab/pyensembl/48)







---

<sup>**[test/test_timings.py, line 29 \[r1\]](https://reviewable.io:443/reviews/hammerlab/pyensembl/48#-Jj5kA4s9OMJkVEXPECt)** ([raw file](https://github.com/hammerlab/pyensembl/blob/7bf1244f264ad8fec8855cd4d3da580636e3afcb/test/test_timings.py#L29)):</sup>
I think this would be more clear if you explicitly pass `n_repeats`, otherwise `n_repeats` and `n_positions_per_contig` get muddied together in my mind.

---

<sup>**[test/test_timings.py, line 46 \[r1\]](https://reviewable.io:443/reviews/hammerlab/pyensembl/48#-Jj5jb_yOjiCHtztjZH5)** ([raw file](https://github.com/hammerlab/pyensembl/blob/7bf1244f264ad8fec8855cd4d3da580636e3afcb/test/test_timings.py#L46)):</sup>
I'm confused. Why is it useful to run them outside of nose?

---

<sup>**[test/timer.py, line 16 \[r1\]](https://reviewable.io:443/reviews/hammerlab/pyensembl/48#-Jj5idmaAZYwg-ItdRXR)** ([raw file](https://github.com/hammerlab/pyensembl/blob/7bf1244f264ad8fec8855cd4d3da580636e3afcb/test/timer.py#L16)):</sup>
Maybe get rid of `end = start`, and instead assert in elapsed that `end != None`?

---

**Comment by iskandr** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/hammerlab/pyensembl/48)







---

<sup>**[test/test_timings.py, line 29 \[r1\]](https://reviewable.io:443/reviews/hammerlab/pyensembl/48#-Jj5kA4s9OMJkVEXPECt)** ([raw file](https://github.com/hammerlab/pyensembl/blob/7bf1244f264ad8fec8855cd4d3da580636e3afcb/test/test_timings.py#L29)):</sup>
I want to hit every chromosome, didn't see an easy way to combine that with a single integer parameter. Suggestions?

---

<sup>**[test/test_timings.py, line 46 \[r1\]](https://reviewable.io:443/reviews/hammerlab/pyensembl/48#-Jj5jb_yOjiCHtztjZH5)** ([raw file](https://github.com/hammerlab/pyensembl/blob/7bf1244f264ad8fec8855cd4d3da580636e3afcb/test/test_timings.py#L46)):</sup>
I want to run them just as benchmarks and get simple timing prints, and nothing else. 

---

**Comment by tavinathanson** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/hammerlab/pyensembl/48)



---

Good to merge

---

<sup>**[test/test_timings.py, line 29 \[r1\]](https://reviewable.io:443/reviews/hammerlab/pyensembl/48#-Jj5kA4s9OMJkVEXPECt)** ([raw file](https://github.com/hammerlab/pyensembl/blob/7bf1244f264ad8fec8855cd4d3da580636e3afcb/test/test_timings.py#L29)):</sup>
I just meant passing `n_repeats=3` instead of having it default to 3. (Wasn't even thinking about`n_loci`.)

---

**Comment by tavinathanson** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/hammerlab/pyensembl/48)







---

<sup>**[pyensembl/database.py, line 70 \[r2\]](https://reviewable.io:443/reviews/hammerlab/pyensembl/48#-Jj5oHFos0EX675ltbaM)** ([raw file](https://github.com/hammerlab/pyensembl/blob/8294cd1a9a17cfb35a71c109f291e479559456c8/pyensembl/database.py#L70)):</sup>
What's going on here?

---

**Comment by iskandr** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/hammerlab/pyensembl/48)







---

<sup>**[test/test_timings.py, line 29 \[r1\]](https://reviewable.io:443/reviews/hammerlab/pyensembl/48#-Jj5kA4s9OMJkVEXPECt)** ([raw file](https://github.com/hammerlab/pyensembl/blob/7bf1244f264ad8fec8855cd4d3da580636e3afcb/test/test_timings.py#L29)):</sup>
`n_repeats` is just for benchmarking accuracy, whereas `n_positions_per_contig` actually controls how long the test runs for. 

---

**Comment by iskandr** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/hammerlab/pyensembl/48)







---

<sup>**[pyensembl/database.py, line 70 \[r2\]](https://reviewable.io:443/reviews/hammerlab/pyensembl/48#-Jj5oHFos0EX675ltbaM)** ([raw file](https://github.com/hammerlab/pyensembl/blob/8294cd1a9a17cfb35a71c109f291e479559456c8/pyensembl/database.py#L70)):</sup>
Huh, what's the change here?

---

**Comment by tavinathanson** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/hammerlab/pyensembl/48)







---

<sup>**[test/test_timings.py, line 29 \[r1\]](https://reviewable.io:443/reviews/hammerlab/pyensembl/48#-Jj5kA4s9OMJkVEXPECt)** ([raw file](https://github.com/hammerlab/pyensembl/blob/7bf1244f264ad8fec8855cd4d3da580636e3afcb/test/test_timings.py#L29)):</sup>
Yeah, it makes sense. I guess you've convinced me that passing in the argument would actually confuse things more.

---

**Comment by iskandr** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/hammerlab/pyensembl/48)







---

<sup>**[pyensembl/database.py, line 70 \[r2\]](https://reviewable.io:443/reviews/hammerlab/pyensembl/48#-Jj5oHFos0EX675ltbaM)** ([raw file](https://github.com/hammerlab/pyensembl/blob/8294cd1a9a17cfb35a71c109f291e479559456c8/pyensembl/database.py#L70)):</sup>
Oh, damnit, uncommitted leakage across branches

---

**Comment by iskandr** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/hammerlab/pyensembl/48)







---

<sup>**[pyensembl/database.py, line 70 \[r2\]](https://reviewable.io:443/reviews/hammerlab/pyensembl/48#-Jj5oHFos0EX675ltbaM)** ([raw file](https://github.com/hammerlab/pyensembl/blob/8294cd1a9a17cfb35a71c109f291e479559456c8/pyensembl/database.py#L70)):</sup>
Also, hitting publish for every comment is going to drive me insane

---

**Comment by iskandr** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/hammerlab/pyensembl/48)







---

<sup>**[pyensembl/database.py, line 70 \[r2\]](https://reviewable.io:443/reviews/hammerlab/pyensembl/48#-Jj5oHFos0EX675ltbaM)** ([raw file](https://github.com/hammerlab/pyensembl/blob/8294cd1a9a17cfb35a71c109f291e479559456c8/pyensembl/database.py#L70)):</sup>
Why isn't Reviewable showing the old version on the left side?

---

**Comment by iskandr** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/hammerlab/pyensembl/48)







---

**Comment by iskandr** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/hammerlab/pyensembl/48)







---

**Pull request merged**
