### PR TITLE
Generalized ReferenceTranscripts into SequenceData, added protein sequences

### PR DESCRIPTION
**Pull request by iskandr**
* Replaced `ReferenceTranscripts` with a more general `SequenceData` class that gives us access to both transcript (cDNA) & protein (amino acid) sequences
* Reduced the amount of state we have to pass into `Gene` & `Transcript` objects by giving them `EnsemblRelease` objects directly. This creates an implicit circular dependency (since `Gene` and `Transcript` are created *by* `EnsemblRelease`) but greatly simplifies access to both the annotation DB and sequence DB from within genes & transcripts.
* Protein & cDNA FASTA paths generated by the same helper: `url_templates.fasta_url`.
* Transcripts now have properties `protein_id` and `protein_sequence`.
* Fixed: some unit tests weren't running since they weren't calling `test_ensembl_releases()`

[Review on Reviewable](https://reviewable.io/reviews/hammerlab/pyensembl/70)

### CODE REVIEW

**Comment by tavinathanson** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/hammerlab/pyensembl/70)

Reviewed files:
- pyensembl/__init__.py @ r1
- pyensembl/common.py @ r1
- pyensembl/database.py @ r2
- pyensembl/ensembl_release.py @ r2
- pyensembl/exon.py @ r1
- pyensembl/gene.py @ r1
- pyensembl/gtf.py @ r1
- pyensembl/locus.py @ r1
- pyensembl/reference_transcripts.py @ r1
- pyensembl/release_info.py @ r1
- pyensembl/search.py @ r2
- pyensembl/sequence_data.py @ r1
- pyensembl/transcript.py @ r2
- pyensembl/url_templates.py @ r1
- setup.py @ r3
- test/data.py @ r2
- test/test_common.py @ r2
- test/test_dataframe_release75.py @ r1
- test/test_download.py @ r1
- test/test_ensembl_object_properties.py @ r1
- test/test_gene_objects.py @ r2
- test/test_id_length.py @ r2
- test/test_reference_transcripts.py @ r1
- test/test_search.py @ r2
- test/test_transcript_objects.py @ r2
- test/test_transcript_sequences.py @ r1





---

<sup>**[pyensembl/common.py, line 19 \[r1\]](https://reviewable.io:443/reviews/hammerlab/pyensembl/70#-JlH5Nt9hODMDCwkXMsA)** ([raw file](https://github.com/hammerlab/pyensembl/blob/2cc6316f5846057dcb79fa6dd5c771e94bc3219e/pyensembl/common.py#L19)):</sup>
Weird that there isn't an obvious library for this!

---

<sup>**[pyensembl/database.py, line 401 \[r3\]](https://reviewable.io:443/reviews/hammerlab/pyensembl/70#-JlHP6X_5ea7w44nAYlv)** ([raw file](https://github.com/hammerlab/pyensembl/blob/8813e595cf27e0829cd616af5fb988c0a9915d3b/pyensembl/database.py#L401)):</sup>
Comment saying what `required` means?

---

<sup>**[pyensembl/ensembl_release.py, line 74 \[r3\]](https://reviewable.io:443/reviews/hammerlab/pyensembl/70#-JlHPdd0CLCBQMS0nJ7n)** ([raw file](https://github.com/hammerlab/pyensembl/blob/8813e595cf27e0829cd616af5fb988c0a9915d3b/pyensembl/ensembl_release.py#L74)):</sup>
Minor, but to reduce complexity and increase readability, what about `SequenceData` doing the `fasta_url` import and call itself?

---

<sup>**[pyensembl/ensembl_release.py, line 208 \[r3\]](https://reviewable.io:443/reviews/hammerlab/pyensembl/70#-JlHPy5pg3jZw--mXXh7)** ([raw file](https://github.com/hammerlab/pyensembl/blob/8813e595cf27e0829cd616af5fb988c0a9915d3b/pyensembl/ensembl_release.py#L208)):</sup>
How about making an `is_valid_transcript_id`/`is_valid_protein_id` in some common area? Seems generally useful.

---

<sup>**[pyensembl/gene.py, line 80 \[r3\]](https://reviewable.io:443/reviews/hammerlab/pyensembl/70#-JlHRBdiJE5dOq5SMCCI)** ([raw file](https://github.com/hammerlab/pyensembl/blob/8813e595cf27e0829cd616af5fb988c0a9915d3b/pyensembl/gene.py#L80)):</sup>
`ensembl_release` doesn't have `__eq__`?

---

<sup>**[pyensembl/sequence_data.py, line 1 \[r3\]](https://reviewable.io:443/reviews/hammerlab/pyensembl/70#-JlHRxC44-9bG2dc4883)** ([raw file](https://github.com/hammerlab/pyensembl/blob/8813e595cf27e0829cd616af5fb988c0a9915d3b/pyensembl/sequence_data.py#L1)):</sup>
I still think it'd be easier for reviews if renames are done separately. So, for example, one commit would use reference_transcripts (but use it as if it's sequence_data), and then another commit would literally just do the rename.

---

<sup>**[pyensembl/sequence_data.py, line 51 \[r3\]](https://reviewable.io:443/reviews/hammerlab/pyensembl/70#-JlHTBlwoUk3m7MARsWf)** ([raw file](https://github.com/hammerlab/pyensembl/blob/8813e595cf27e0829cd616af5fb988c0a9915d3b/pyensembl/sequence_data.py#L51)):</sup>
That's just awful.

I think this would be more readable if extracted out into `self.local_filename = add_release_to_filename_if_not_there` or something

---

<sup>**[pyensembl/sequence_data.py, line 94 \[r3\]](https://reviewable.io:443/reviews/hammerlab/pyensembl/70#-JlHU7Bs6z5gx331S7pu)** ([raw file](https://github.com/hammerlab/pyensembl/blob/8813e595cf27e0829cd616af5fb988c0a9915d3b/pyensembl/sequence_data.py#L94)):</sup>
So this is better than just `self.local_filename == other.local_filename`? Curious what your thoughts are there. I guess it depends on whether we view equality as a pre-lazy loading or post-lazy loading property?

---

<sup>**[pyensembl/sequence_data.py, line 153 \[r3\]](https://reviewable.io:443/reviews/hammerlab/pyensembl/70#-JlHUXXXpCBtdg9dkHyV)** ([raw file](https://github.com/hammerlab/pyensembl/blob/8813e595cf27e0829cd616af5fb988c0a9915d3b/pyensembl/sequence_data.py#L153)):</sup>
`True` and `False` are no longer necessary (and the associated comment).

---

<sup>**[pyensembl/sequence_data.py, line 224 \[r3\]](https://reviewable.io:443/reviews/hammerlab/pyensembl/70#-JlHUoDwAJkI7pkQBLFc)** ([raw file](https://github.com/hammerlab/pyensembl/blob/8813e595cf27e0829cd616af5fb988c0a9915d3b/pyensembl/sequence_data.py#L224)):</sup>
I think this can be extracted out into the same place as `is_valid_protein_id`, etc.

---

<sup>**[pyensembl/sequence_data.py, line 233 \[r3\]](https://reviewable.io:443/reviews/hammerlab/pyensembl/70#-JlHV5qo3xj7u-kEsMhL)** ([raw file](https://github.com/hammerlab/pyensembl/blob/8813e595cf27e0829cd616af5fb988c0a9915d3b/pyensembl/sequence_data.py#L233)):</sup>
Maybe a bit confusing that `clear_cache` doesn't do anything with this in memory cache, even though they're entirely different?

---

<sup>**[pyensembl/transcript.py, line 78 \[r3\]](https://reviewable.io:443/reviews/hammerlab/pyensembl/70#-JlHVXj32d3GFoORXLW7)** ([raw file](https://github.com/hammerlab/pyensembl/blob/8813e595cf27e0829cd616af5fb988c0a9915d3b/pyensembl/transcript.py#L78)):</sup>
Curious about what inspired you to do all this `if/else/error` re-ordering in multiple files.

---

<sup>**[pyensembl/transcript.py, line 177 \[r3\]](https://reviewable.io:443/reviews/hammerlab/pyensembl/70#-JlHVtv3i5EBhYxWuZji)** ([raw file](https://github.com/hammerlab/pyensembl/blob/8813e595cf27e0829cd616af5fb988c0a9915d3b/pyensembl/transcript.py#L177)):</sup>
Why is this a TODO, now that you have the decorator?

---

**Comment by iskandr** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/hammerlab/pyensembl/70)







---

<sup>**[pyensembl/common.py, line 19 \[r1\]](https://reviewable.io:443/reviews/hammerlab/pyensembl/70#-JlH5Nt9hODMDCwkXMsA)** ([raw file](https://github.com/hammerlab/pyensembl/blob/2cc6316f5846057dcb79fa6dd5c771e94bc3219e/pyensembl/common.py#L19)):</sup>
Yeah, I tried to find one and they all do too much (e.g. use `__repr__` for cache keys, have timeouts and cache limits, serialize to disk, &c). I'd use `lru_cache` if it ever got back-ported from Python 3.x!

---

<sup>**[pyensembl/ensembl_release.py, line 74 \[r3\]](https://reviewable.io:443/reviews/hammerlab/pyensembl/70#-JlHPdd0CLCBQMS0nJ7n)** ([raw file](https://github.com/hammerlab/pyensembl/blob/8813e595cf27e0829cd616af5fb988c0a9915d3b/pyensembl/ensembl_release.py#L74)):</sup>
So, pass `species`, `server` and `sequence_type` to `SequenceData`? I was considering that but the class seems simpler/less magical if it's just given a FASTA URL and expected to download/index that particular FASTA (all the Ensembl specific stuff stays in `EnsemblRelease`)

---

<sup>**[pyensembl/ensembl_release.py, line 208 \[r3\]](https://reviewable.io:443/reviews/hammerlab/pyensembl/70#-JlHPy5pg3jZw--mXXh7)** ([raw file](https://github.com/hammerlab/pyensembl/blob/8813e595cf27e0829cd616af5fb988c0a9915d3b/pyensembl/ensembl_release.py#L208)):</sup>
Made `require_human_transcript_id` and `require_human_protein_id` in `common`

---

<sup>**[pyensembl/gene.py, line 80 \[r3\]](https://reviewable.io:443/reviews/hammerlab/pyensembl/70#-JlHRBdiJE5dOq5SMCCI)** ([raw file](https://github.com/hammerlab/pyensembl/blob/8813e595cf27e0829cd616af5fb988c0a9915d3b/pyensembl/gene.py#L80)):</sup>
Weird, I though it did! Just added one. 

---

<sup>**[pyensembl/sequence_data.py, line 1 \[r3\]](https://reviewable.io:443/reviews/hammerlab/pyensembl/70#-JlHRxC44-9bG2dc4883)** ([raw file](https://github.com/hammerlab/pyensembl/blob/8813e595cf27e0829cd616af5fb988c0a9915d3b/pyensembl/sequence_data.py#L1)):</sup>
Well, it's a rename and a change of functionality. It wouldn't really make sense for `ReferenceTranscripts` to also be used for protein sequences. Not sure if there's a functional intermediate state we'd want to be in after a single smaller PR

---

<sup>**[pyensembl/sequence_data.py, line 94 \[r3\]](https://reviewable.io:443/reviews/hammerlab/pyensembl/70#-JlHU7Bs6z5gx331S7pu)** ([raw file](https://github.com/hammerlab/pyensembl/blob/8813e595cf27e0829cd616af5fb988c0a9915d3b/pyensembl/sequence_data.py#L94)):</sup>
I guess you might want to compare whether two SequenceData objects wrap the same sequences even if you haven't downloaded them yet. Changing this. 

---

<sup>**[pyensembl/sequence_data.py, line 233 \[r3\]](https://reviewable.io:443/reviews/hammerlab/pyensembl/70#-JlHV5qo3xj7u-kEsMhL)** ([raw file](https://github.com/hammerlab/pyensembl/blob/8813e595cf27e0829cd616af5fb988c0a9915d3b/pyensembl/sequence_data.py#L233)):</sup>
That's a bug!

---

<sup>**[pyensembl/transcript.py, line 78 \[r3\]](https://reviewable.io:443/reviews/hammerlab/pyensembl/70#-JlHVXj32d3GFoORXLW7)** ([raw file](https://github.com/hammerlab/pyensembl/blob/8813e595cf27e0829cd616af5fb988c0a9915d3b/pyensembl/transcript.py#L78)):</sup>
I'd rather see the default (not-error) case first, makes the logic easier for me to follow

---

<sup>**[pyensembl/transcript.py, line 177 \[r3\]](https://reviewable.io:443/reviews/hammerlab/pyensembl/70#-JlHVtv3i5EBhYxWuZji)** ([raw file](https://github.com/hammerlab/pyensembl/blob/8813e595cf27e0829cd616af5fb988c0a9915d3b/pyensembl/transcript.py#L177)):</sup>
I added the decorator and forgot to come back, fixed

---

**Comment by tavinathanson** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/hammerlab/pyensembl/70)

Reviewed files:
- pyensembl/common.py @ r4
- pyensembl/database.py @ r4
- pyensembl/ensembl_release.py @ r4
- pyensembl/exon.py @ r4
- pyensembl/sequence_data.py @ r4
- pyensembl/transcript.py @ r4
- test/test_transcript_sequences.py @ r5

---

Merge away :+1:

---

<sup>**[pyensembl/ensembl_release.py, line 75 \[r3\]](https://reviewable.io:443/reviews/hammerlab/pyensembl/70#-JlHPdd0CLCBQMS0nJ7n)** ([raw file](https://github.com/hammerlab/pyensembl/blob/8813e595cf27e0829cd616af5fb988c0a9915d3b/pyensembl/ensembl_release.py#L75)):</sup>
Well, my understanding is that it already has that information via getting passed `ensembl_release`, though that feels like abuse. In any event point about less magic in SequenceData seems valid! :+1:

---

<sup>**[pyensembl/sequence_data.py, line 1 \[r3\]](https://reviewable.io:443/reviews/hammerlab/pyensembl/70#-JlHRxC44-9bG2dc4883)** ([raw file](https://github.com/hammerlab/pyensembl/blob/8813e595cf27e0829cd616af5fb988c0a9915d3b/pyensembl/sequence_data.py#L1)):</sup>
Yup, that's why I said 1 commit (within a larger PR) vs. 1 PR. (That would let me diff that commit before it gets renamed.)

---

**Comment by tavinathanson** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/hammerlab/pyensembl/70)



---

(Wait, I retract that. 1 second.)

---

**Comment by tavinathanson** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/hammerlab/pyensembl/70)



---

Okay, merge away for real :)

---

**Comment by iskandr** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/hammerlab/pyensembl/70)







---

<sup>**[pyensembl/sequence_data.py, line 1 \[r3\]](https://reviewable.io:443/reviews/hammerlab/pyensembl/70#-JlHRxC44-9bG2dc4883)** ([raw file](https://github.com/hammerlab/pyensembl/blob/8813e595cf27e0829cd616af5fb988c0a9915d3b/pyensembl/sequence_data.py#L1)):</sup>
Oh! Sorry, I misunderstood. Gotcha. 

---

**Pull request merged**
