### PR TITLE
Added "gene" property to Transcript objects which gives access to the parent Gene

### PR DESCRIPTION
**Pull request by iskandr**
[Review on Reviewable](https://reviewable.io/reviews/hammerlab/pyensembl/87)

### CODE REVIEW

**Comment by arahuja** [comment]
Looks like there are CI issues - is that expected? 

I can't comment on this line, but in `__init__`:
```
     def __init__(
             self,
             transcript_id,
             transcript_name,
             contig,
             start,
             end,
             strand,
             biotype,
             gene_id,
             gene_name,
```

`Transcript probably doesn't need `gene_name` anymore since you can get the from `gene`, or is that costly?

**Comment by iskandr** [comment]
Yeah, "fixing Travis" has been on the TODO list for a long time. I think @tavinathanson has some idea for it but it's not done yet.

**Comment by tavinathanson** [comment]
Yeah, I started on the GTF minification but haven't looked at that for a few weeks. Just disabled Travis CI so we stop getting errors.

**Comment by iskandr** [comment]
@arahuja Removed `gene_name` from the Transcript constructor, you're right that I can just use the `Gene` object instead.

**Pull request merged**
